name = "manolito-infinito"
main = "index.js"  # o "src/index.js"
compatibility_date = "2024-07-21"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[assets]
binding = "ASSETS"
directory = "./assets"  # o donde tengas los archivos estáticos
